# model.py 

import numpy as np
import yfinance as yf
import contextlib
import io



def create_asset(Ticker, qty_purchased, purchase_price):
    yf_ticker = yf.Ticker(Ticker)

    info = yf_ticker.info

    name = info.get('shortName', Ticker)

    sector = info.get('sector', "Unknown")

    asset_class = info.get('quoteType', "Unknown")

    transac_val = qty_purchased * purchase_price

    curr_price = (
        info.get('currentPrice')
        or info.get('regularMarketPrice')
        or info.get('navPrice')
        or info.get('previousClose')
    )

    if curr_price is None:
        return None

    curr_val = qty_purchased * curr_price

    asset = {
        'Ticker': Ticker,
        'Name': name,
        'Sector': sector,
        'Asset Class': asset_class,
        'Quantity': qty_purchased,
        'Purchase Price': purchase_price,
        'Transaction Value': transac_val,
        'Current Price': curr_price,
        'Current Value': curr_val,
    }

    return asset


def get_history(Ticker, start_date, end_date):
    history = yf.Ticker(Ticker).history(start=start_date, end=end_date)
    return history

def validate_ticker(Ticker):
    try:
        with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
            data = yf.Ticker(Ticker).history(period='1d')
        return not data.empty
    except Exception:
        return False

def get_plot_history(Ticker, start_date, end_date):
    history = yf.Ticker(Ticker).history(start=start_date, end=end_date)
    return history

def sim_gbm_paths(P0, mu, sigma, T, n_steps, n_paths):
    """
    docstring...
    """
    dt = T / n_steps
    np.random.seed(42)           # To reproduce the given psuedo random sequence generated by np.random.
    Z = np.random.standard_normal((n_steps, n_paths))     # Multiply n_steps and n_paths? So every step in time you sample the 100.000 paths.

    daily_pf_return = np.exp((mu - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * Z)

    paths = np.zeros((n_steps + 1, n_paths))            
    paths[0] = P0
    for t in range(1, n_steps + 1):
        paths[t] = paths[t-1] * daily_pf_return[t-1]
    
    return paths